RCAL-704: Updates needed for running the resample step
PaulHuwe/rad pull request #3
Opened 2024-01-23 19:13 UTC by stscieisenhamer

WIP [RCAL-704](https://jira.stsci.edu/browse/RCAL-704)
WIP [RAD-138](https://jira.stsci.edu/browse/RAD-138)

This PR updates PR#334 to resolve issues with running the resample step with the new L3 metadata.

Issues resolved:
- Loss of `meta.filename`

**Checklist**
- [ ] Schema changes discussed at RAD Review Board meeting
- [ ] Added entry in `CHANGES.rst` under the corresponding subsection
- [ ] Updated relevant roman_datamodels utilities and tests
- [ ] Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/

2024-01-26 12:57 UTC, stscieisenhamer commented
A discussion point, of which I might of missed something. The upper level meta represented by `basic-1.0.0` schema was originally removed. This seemed odd since important info such a s`calibration_software_version` and the needed `filename` and the rearrangement of `model_type` and `telescope`, making this basic info inconsistent between L2 and L3.

This PR (and related rdm one) restores it. Just now shower-thought realized that the sdp and prd versions are L2-dependent and could be removed, though having at least the sdp version is still relevant; no doubt this can be retrieved from the sdp environment when the l3 pipeline runs. Just felt that the basic info such as this should be consistent. It can be reverted if necessary. This can easily be reverted. This also removes the need for L3-specific handling of `model_type` in the maker utils and tests.

2024-01-26 20:55 UTC, schlafly commented
Yeah, I agree that it's reasonable to include the basic schema in addition to the other L3 stuff.  At least I know what all of those things mean even if I don't really understand why we put the file name and date inside the file.

2024-01-26 21:00 UTC, PaulHuwe requested changes

2024-01-26 21:00 UTC, PaulHuwe commented on src/rad/resources/schemas/wfi_mosaic-1.0.0.yaml
> +      - $ref: asdf://stsci.edu/datamodels/roman/schemas/basic-1.0.0
Could you please specify the keywords you need from basic and put them in mosaic_basic-1.0.0? We are trying to avoid root level keywords in this schema.

2024-01-28 03:02 UTC, stscieisenhamer commented
Closing this PR in favor of a more appropriate future one.

2024-01-28 03:02 UTC, closed without merging